name: wavenadmin
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  get_it: ^9.2.0
  flutter_bloc: ^9.1.1
  go_router: ^17.0.1
  google_fonts: ^6.3.3
  logger: ^2.6.2
  flutter_svg: ^2.2.3
  fl_chart: ^0.69.0
  table_calendar: ^3.2.0
  syncfusion_flutter_calendar: ^31.2.18
  file_picker: ^10.3.7
  path: ^1.9.1
  http: ^1.6.0
  flutter_secure_storage: ^10.0.0
  lottie: ^3.3.2
  flutter_riverpod: ^3.0.3
  dropdown_search: ^6.0.2
  image_picker: ^1.2.1
  web: ^1.1.1
  intl: ^0.20.1
  cached_network_image: ^3.4.1
  equatable: ^2.0.7
  url_launcher: ^6.3.2
  app_links: ^6.3.3
  
  
  


  riverpod_annotation: ^3.0.3
  
  dio: ^5.9.0
  json_annotation: ^4.9.0
  bloc: ^9.1.0
  meta: ^1.17.0
  permission_handler: ^12.0.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  json_serializable: ^6.11.2
  riverpod_generator: ^3.0.3
  build_runner: ^2.10.4

flutter:
  uses-material-design: true
  assets:
    -  assets/icon/sidenavigation/
    -  assets/icon/content/
    -  assets/lottie/
